title: BIRT Incident Response & Triage
description: Tutorials, How-To's and information about BIRT
show_downloads: true
google_analytics: G-XJLLPWY1P4
remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme